import { Bot, CheckCircle2, Eye, FlaskConical, Gauge, UserCheck } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { humanize } from '@/utils/format'

const PRIORITY_TONES = { low: 'slate', medium: 'amber', high: 'orange', critical: 'red' }

export function PriorityBadge({ priority }) {
  if (!priority) return <Badge tone="slate">Not assessed</Badge>
  return <Badge tone={PRIORITY_TONES[priority]}>{humanize(priority)}</Badge>
}

const ISSUE_TONES = {
  reported: 'blue',
  analysis_failed: 'red',
  awaiting_review: 'amber',
  work_order_approved: 'green',
  work_order_rejected: 'slate',
}

export function IssueStatusBadge({ status }) {
  return <Badge tone={ISSUE_TONES[status] || 'slate'}>{humanize(status)}</Badge>
}

const WO_TONES = { pending_review: 'amber', approved: 'green', rejected: 'red', superseded: 'slate' }

export function WorkOrderStatusBadge({ status }) {
  return <Badge tone={WO_TONES[status] || 'slate'}>{humanize(status)}</Badge>
}

const SEVERITY_TONES = { normal: 'green', warning: 'amber', critical: 'red', unknown: 'slate' }

export function SeverityBadge({ severity }) {
  return <Badge tone={SEVERITY_TONES[severity] || 'slate'}>{humanize(severity)}</Badge>
}

const EQUIPMENT_STATUS_TONES = { operational: 'green', degraded: 'amber', down: 'red', maintenance: 'blue' }

export function EquipmentStatusBadge({ status }) {
  return <Badge tone={EQUIPMENT_STATUS_TONES[status] || 'slate'}>{humanize(status)}</Badge>
}

export function ConfidenceBadge({ confidence }) {
  const tone = { low: 'slate', medium: 'blue', high: 'violet' }[confidence] || 'slate'
  return <Badge tone={tone}>{humanize(confidence)} confidence</Badge>
}

/**
 * Provenance labels distinguish where a statement came from:
 * observed fact, deterministic rule, AI hypothesis, or technician-confirmed.
 */
const PROVENANCE = {
  observed: { label: 'Observed', tone: 'slate', icon: Eye },
  rule: { label: 'Rule-based finding', tone: 'blue', icon: Gauge },
  ai: { label: 'AI hypothesis', tone: 'violet', icon: Bot },
  technician: { label: 'Technician-confirmed', tone: 'green', icon: UserCheck },
}

export function ProvenanceTag({ kind }) {
  const p = PROVENANCE[kind]
  const Icon = p.icon
  return (
    <Badge tone={p.tone}>
      <Icon className="size-3" aria-hidden="true" />
      {p.label}
    </Badge>
  )
}

export function SimulatedBadge({ simulated }) {
  if (simulated) {
    return (
      <Badge tone="amber" title="Generated by the deterministic demo provider, not an AI model">
        <FlaskConical className="size-3" aria-hidden="true" /> Simulated (demo mode)
      </Badge>
    )
  }
  return (
    <Badge tone="violet">
      <CheckCircle2 className="size-3" aria-hidden="true" /> Live AI (Gemini)
    </Badge>
  )
}
