import { Suspense, useState } from 'react'
import { Outlet } from 'react-router-dom'
import { DatabaseZap, FlaskConical, WifiOff } from 'lucide-react'
import { Sidebar } from '@/components/layout/Sidebar'
import { Topbar } from '@/components/layout/Topbar'
import { LoadingRows } from '@/components/common/States'
import { useHealth, useWorkOrders } from '@/hooks/useApi'
import { API_URL } from '@/services/api'

/** Surfaces real backend status so the UI never implies persistence or live AI it does not have. */
function SystemBanner() {
  const health = useHealth()
  if (health.isLoading) return null
  if (health.isError) {
    return (
      <div className="flex items-center gap-2 border-b border-red-200 bg-red-50 px-6 py-2 text-sm text-red-800" role="alert">
        <WifiOff className="size-4 shrink-0" /> Cannot reach the API at {API_URL}. Data shown may be unavailable.
      </div>
    )
  }
  const h = health.data
  return (
    <>
      {h.database.status !== 'ok' && (
        <div className="flex items-center gap-2 border-b border-red-200 bg-red-50 px-6 py-2 text-sm text-red-800" role="alert">
          <DatabaseZap className="size-4 shrink-0" /> Database unavailable — changes cannot be saved right now.
        </div>
      )}
      {h.database.status === 'ok' && !h.database.persistent && (
        <div className="flex items-center gap-2 border-b border-amber-200 bg-amber-50 px-6 py-2 text-sm text-amber-900">
          <DatabaseZap className="size-4 shrink-0" /> In-memory database: data is NOT persisted and resets when the API restarts.
        </div>
      )}
      {h.ai.is_simulated && (
        <div className="flex items-center gap-2 border-b border-amber-200 bg-amber-50/70 px-6 py-1.5 text-xs text-amber-900">
          <FlaskConical className="size-3.5 shrink-0" /> Demo mode: analyses are simulated by a deterministic provider, not generated by Gemini.
        </div>
      )}
    </>
  )
}

export default function DashboardLayout() {
  const [open, setOpen] = useState(false)
  const pending = useWorkOrders({ status: 'pending_review' })
  return (
    <div className="min-h-screen">
      <Sidebar open={open} onClose={() => setOpen(false)} pendingCount={pending.data?.length || 0} />
      <div className="lg:pl-64">
        <Topbar onMenu={() => setOpen(true)} />
        <SystemBanner />
        <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <Suspense fallback={<LoadingRows rows={6} />}>
            <Outlet />
          </Suspense>
        </main>
      </div>
    </div>
  )
}
